#pragma once

#include <mithril/types.hpp>

constexpr u64 ELF_PROGRAM_HEADER_OFFSET = 0x20;
constexpr u64 ELF_PROGRAM_HEADER_ENTRY_SIZE = 0x36;
constexpr u64 ELF_PROGRAM_HEADER_NUM_ENTRIES = 0x38;

constexpr u64 ELF_SECTION_HEADER_OFFSET = 0x28;
constexpr u64 ELF_SECTION_HEADER_ENTRY_SIZE = 0x3A;
constexpr u64 ELF_SECTION_HEADER_NUM_ENTRIES = 0x3C;

constexpr u64 ELF_DYNAMIC_SECTION_PHT_TYPE = 0x02;
