#include <map>

enum KeyCode {
    KeyNone,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    /*KeyPAD_0,
    KeyPAD_1,
    KeyPAD_2,
    KeyPAD_3,
    KeyPAD_4,
    KeyPAD_5,
    KeyPAD_6,
    KeyPAD_7,
    KeyPAD_8,
    KeyPAD_9,
    KeyPAD_DIVIDE,
    KeyPAD_MULTIPLY,
    KeyPAD_MINUS,
    KeyPAD_PLUS,
    KeyPAD_ENTER,
    KeyPAD_DECIMAL,
    KeyLBRACKET,
    KeyRBRACKET,
    KeySEMICOLON,
    KeyAPOSTROPHE,
    KeyBACKQUOTE,
    KeyCOMMA,
    KeyPERIOD,
    KeySLASH,
    KeyBACKSLASH,
    KeyMINUS,
    KeyEQUAL,
    KeyENTER,*/
    KeySpace = 66,
    KeyBackspace,
    KeyTab,
    KeyCapslock,
    /*KeyNUMLOCK,
    KeyESCAPE,
    KeySCROLLLOCK,
    KeyINSERT,
    KeyDELETE,
    KeyHOME,
    KeyEND,
    KeyPAGEUP,
    KeyPAGEDOWN,
    KeyBREAK,*/
    KeyLeftShift = 80,
    // KeyRSHIFT,
    KeyLeftAlt = 82,
    // KeyRALT,
    KeyLeftControl = 84,
    /*KeyRCONTROL,
    KeyLWIN,
    KeyRWIN,
    KeyAPP,
    KeyUP,
    KeyLEFT,
    KeyDOWN,
    KeyRIGHT,
    KeyF1,
    KeyF2,
    KeyF3,
    KeyF4,
    KeyF5,
    KeyF6,
    KeyF7,
    KeyF8,
    KeyF9,
    KeyF10,
    KeyF11,
    KeyF12,
    KeyCAPSLOCKTOGGLE,
    KeyNUMLOCKTOGGLE,
    KeySCROLLLOCKTOGGLE,*/

    MouseLeft = 317,
    MouseRight,
    MouseMiddle,
    Mouse4,
    Mouse5,
    // MouseWheelUp,
    // MouseWheelDown,
};

struct EnumEntry {
    KeyCode key;
    const char *name;
};

const std::map<KeyCode, const char *> key_code_names = {
    {KeyCode::Key0, "Key0"},
    {KeyCode::Key1, "Key1"},
    {KeyCode::Key2, "Key2"},
    {KeyCode::Key3, "Key3"},
    {KeyCode::Key4, "Key4"},
    {KeyCode::Key5, "Key5"},
    {KeyCode::Key6, "Key6"},
    {KeyCode::Key7, "Key7"},
    {KeyCode::Key8, "Key8"},
    {KeyCode::Key9, "Key9"},
    {KeyCode::KeyA, "KeyA"},
    {KeyCode::KeyB, "KeyB"},
    {KeyCode::KeyC, "KeyC"},
    {KeyCode::KeyD, "KeyD"},
    {KeyCode::KeyE, "KeyE"},
    {KeyCode::KeyF, "KeyF"},
    {KeyCode::KeyG, "KeyG"},
    {KeyCode::KeyH, "KeyH"},
    {KeyCode::KeyI, "KeyI"},
    {KeyCode::KeyJ, "KeyJ"},
    {KeyCode::KeyK, "KeyK"},
    {KeyCode::KeyL, "KeyL"},
    {KeyCode::KeyM, "KeyM"},
    {KeyCode::KeyN, "KeyN"},
    {KeyCode::KeyO, "KeyO"},
    {KeyCode::KeyP, "KeyP"},
    {KeyCode::KeyQ, "KeyQ"},
    {KeyCode::KeyR, "KeyR"},
    {KeyCode::KeyS, "KeyS"},
    {KeyCode::KeyT, "KeyT"},
    {KeyCode::KeyU, "KeyU"},
    {KeyCode::KeyV, "KeyV"},
    {KeyCode::KeyW, "KeyW"},
    {KeyCode::KeyX, "KeyX"},
    {KeyCode::KeyY, "KeyY"},
    {KeyCode::KeyZ, "KeyZ"},
    {KeyCode::KeySpace, "KeySpace"},
    {KeyCode::KeyBackspace, "KeyBackspace"},
    {KeyCode::KeyTab, "KeyTab"},
    {KeyCode::KeyCapslock, "KeyCapslock"},
    {KeyCode::KeyLeftShift, "KeyLeftShift"},
    {KeyCode::KeyLeftAlt, "KeyLeftAlt"},
    {KeyCode::KeyLeftControl, "KeyLeftControl"},
    {KeyCode::MouseLeft, "MouseLeft"},
    {KeyCode::MouseRight, "MouseRight"},
    {KeyCode::MouseMiddle, "MouseMiddle"},
    {KeyCode::Mouse4, "Mouse4"},
    {KeyCode::Mouse5, "Mouse5"}};
