#ifndef BONES_H
#define BONES_H

enum Bones {
    BONE_PELVIS = 0,
    BONE_SPINE1 = 2,
    BONE_SPINE2 = 4,
    BONE_NECK = 5,
    BONE_HEAD = 6,
    BONE_LEFT_SHOULDER = 8,
    BONE_LEFT_ELBOW = 9,
    BONE_LEFT_HAND = 10,
    BONE_RIGHT_SHOULDER = 13,
    BONE_RIGHT_ELBOW = 14,
    BONE_RIGHT_HAND = 15,
    BONE_LEFT_HIP = 22,
    BONE_LEFT_KNEE = 23,
    BONE_LEFT_FOOT = 24,
    BONE_RIGHT_HIP = 25,
    BONE_RIGHT_KNEE = 26,
    BONE_RIGHT_FOOT = 27,
};

#endif
